### ISSUE TITLE
var userConsent = await Appodeal.fetchConsentInfo() return null exception 

### ISSUE THREAD

**Issue by devuserPP** [vegidio/flutter-appodeal#38]
Testing on Android
Exception has occurred.
_TypeError (type 'Null' is not a subtype of type 'String')

    • Flutter version 2.2.3 at C:\_SDK\flutter
    • Framework revision f4abaa0735 (10 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
    • appodeal_flutter: ^1.1.0

When I run the app for first time, `userConsent.status == ConsentStatus.UNKNOWN` return true and I call `Appodeal.requestConsentAuthorization();`. choose I agree, so it works fine.

When I run the app for second and more time, always stuck on "var userConsent = await Appodeal.fetchConsentInfo()" with  null exception.
Any ideas?

**Comment by vegidio** [comment]
In order to help debug this, can you please clone this repo and run the test app and the `example` folder? There's a button there to request consent and also display the consent info. Please click on those buttons a few times and let me know if it also crashes for you.

Thanks.

**Comment by devuserPP** [comment]
please check my code example, same error. Im not able to fix it. thanks a lot.

**Comment by vegidio** [comment]
Thanks, this will be very helpful to debug the problem.

**Comment by vegidio** [comment]
I found the bug; I will release a new version of the plugin with a fix this weekend.

Thanks for helping with the investigation.

**Comment by vegidio** [comment]
Version [1.1.1](https://github.com/vegidio/flutter-appodeal/releases/tag/1.1.1) with the fix has been deployed to pub.dev
